name: 42authcraft
version: 1.0.2
author: RPDJF
main: ch.ruinformatique.fortytwoauthcraft.FortytwoAuthCraft
api-version: 1.21
commands:
  login:
    description: Login to 42 network
    usage: /<command>